### ISSUE TITLE
reformatting field names according to data warehouse

### ISSUE THREAD

**Issue by axelazaid** [dbt-labs/facebook-ads#18]
possibly create a macro that reformats nested fields as they come in from Stitch so that we don't have to rewrite models just to accommodate minor syntax differences

for example: 
`creative__id` (double underscore that is redshift-specific) vs. `creative['id']` (single bracket that calls a subfield; snowflake-specific)

**Comment by DylanBaker** [comment]
Bigquery syntax would be `creative.id` here. We were going to create a PR for just BigQuery, but would be keen to discuss how this might be implemented in a more database agnostic way.

**Comment by DylanBaker** [comment]
```jinja 

{% macro nested_field(field, subfields) %}

    {{ adapter_macro('facebook_ads.nested_field', field, subfields) }}

{% endmacro %}

{% macro default__nested_field(field, subfields) %}

{{field}}__{{ subfields|join('__') }}

{% endmacro %}

{% macro bigquery__nested_field(field, subfields) %}

{{field}}.{{ subfields|join('.') }}

{% endmacro %}

{% macro snowflake__nested_field(field, subfields) %}

{{field ~ "['" ~ subfields|join("']['") ~ "']" }} 

{%- endmacro %}

```

**Comment by DylanBaker** [comment]
`{{ nested_field('creative',['id']) }}` would compile to:
* `creative.id` on BigQuery
* `creative['id']` on Snowflake
* `creative__id` everywhere else

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
