### ISSUE TITLE
stitch_fb_ad_insights fails build if no canvas adverts in use (column doesn't exist)

### ISSUE THREAD

**Issue by Ken-Lo** [dbt-labs/facebook-ads#29]
In `macros/stitch/base/stitch_fb_ad_insights.sql`, it is assumed that the `canvas_avg_view_percent` and `canvas_avg_view_time` columns exist in the base table created by Stitch.

This is not always the case. For advertisers that don't use the canvas advertising format, this column is always `NULL` in the base data set and as such, Stitch does not create a column for it.

We are currently working around this by pointing ad_insights_table at our own intermediate table which then adds in these two null columns:

In packages.yml:
 ` ads_insights_table: "{{ref('stg_facebook_ad_insights')}}"`

Within the staging table:
```
select 
    *,
    cast(null as int64) as canvas_avg_view_percent,
    cast(null as int64) as canvas_avg_view_time
from stitch_facebook_ads.ads_insights
```

I think there are really two issues here:
1. The table build will fail for advertisers that don't use the canvas advertising format (maybe these should be flags instead?).
2. We use a lot of video advertising, which pulls through a lot of additional columns within the Stitch base table. We would ideally like these to be exposed within the DBT tables, but presumably not all other advertisers will also be using these formats?

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
