### ISSUE TITLE
Compilation Error in model "fb_ad_creatives__child_links"

### ISSUE THREAD

**Issue by QIXIONG** [dbt-labs/facebook-ads#41]
### Describe the bug

Running with dbt=0.18.0
Encountered an error:
Compilation Error in model fb_ad_creatives__child_links (models\router\stitch\fb_ad_creatives__child_links.sql)
  __call__() got an unexpected keyword argument 'packages'

  > in macro stitch_fb_ad_creatives__child_links (macros\stitch\base\stitch_fb_ad_creatives__child_links.sql)
  > called by macro default__stitch_fb_ad_creatives__child_links (macros\stitch\base\stitch_fb_ad_creatives__child_links.sql)
  > called by model fb_ad_creatives__child_links (models\router\stitch\fb_ad_creatives__child_links.sql)

### Steps to reproduce

I just added one model that is referring the package:

select *
from {{ref('facebook_ads', 'fb_ads_xf')}}

### Expected results

this code should work?

### Actual results

the error msg above

### Screenshots and log output

(bq_dbt) C:\Users\xioq311\.dbt\dbt-ga>dbt run
Running with dbt=0.18.0
Encountered an error:
Compilation Error in model fb_ad_creatives__child_links (models\router\stitch\fb_ad_creatives__child_links.sql)
  __call__() got an unexpected keyword argument 'packages'

  > in macro stitch_fb_ad_creatives__child_links (macros\stitch\base\stitch_fb_ad_creatives__child_links.sql)
  > called by macro default__stitch_fb_ad_creatives__child_links (macros\stitch\base\stitch_fb_ad_creatives__child_links.sql)
  > called by model fb_ad_creatives__child_links (models\router\stitch\fb_ad_creatives__child_links.sql)

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: fishtown-analytics/dbt_utils
    version: [">=0.6.0", "<0.7.0"]

  - git: "https://github.com/fishtown-analytics/facebook-ads.git"
    revision: 0.6.0

**Which database are you using dbt with?**
- [ ] bigquery

**The output of `dbt --version`:**
```
installed version: 0.18.0
   latest version: 0.18.0

Up to date!

Plugins:
  - bigquery: 0.18.0
  - postgres: 0.18.0
  - redshift: 0.18.0
```

**The operating system you're using:**
windows10

**The output of `python --version`:**
Python 3.7.0

**Comment by QIXIONG** [comment]
Sorry - not sure why it's labelled as bug...I just need some help with this issue...still learning dbt and git.

**Comment by jtcohen6** [comment]
You're right, I think this is a bug!

We accidentally added a `packages` argument to this line when updating the package for v0.18.0 (using `adapter.dispatch`):

https://github.com/fishtown-analytics/facebook-ads/blob/be59e6734ef497b08e7afa409f74736836fd29f7/macros/stitch/base/stitch_fb_ad_creatives__child_links.sql#L17

That line should just be
```sql
select * from {{ var('ad_creatives__child_links_table') }}
```

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
