### ISSUE TITLE
Non working configuration for data loaded by Stitch.

### ISSUE THREAD

**Issue by escapedoc** [dbt-labs/facebook-ads#43]
Hi, there!
It seems, that the current package version is not suitable for use with Stitch.
According to config, we need to point `ad_creatives__child_links_table` to some table loaded by stitch.
But stitch doesn't load anything like that to DWH.

Anybody solved that issue?

**Comment by AlexStansfield** [comment]
Just trying to set this up too. I have the same issue.

```
Running with dbt=0.19.0
Encountered an error:
Compilation Error in model fb_ad_creatives__child_links (models/router/stitch/fb_ad_creatives__child_links.sql)
  __call__() got an unexpected keyword argument 'packages'

  > in macro stitch_fb_ad_creatives__child_links (macros/stitch/base/stitch_fb_ad_creatives__child_links.sql)
  > called by macro default__stitch_fb_ad_creatives__child_links (macros/stitch/base/stitch_fb_ad_creatives__child_links.sql)
  > called by model fb_ad_creatives__child_links (models/router/stitch/fb_ad_creatives__child_links.sql)
```

**Comment by AlexStansfield** [comment]
Sorry think my error was related to #41, am creating a PR with a fix.

@escapedoc can I ask what data warehouse you're using? We have bigquery and it also doesn't have a table for `ad_creatives__child_links_table`, I've also created a fix for this.

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
