### ISSUE TITLE
Multiple Configurations support

### ISSUE THREAD

**Issue by AlexStansfield** [dbt-labs/facebook-ads#45]
I'm pretty sure this doesn't work currently but any suggestions on how to make it work would be gratefully received.

We have two facebook ads accounts. For different business units. We have stitchdata putting them into two sets of tables in big query. However we found with this plugin we can only configure 1 set of tables.

Is there any way to make this work with 2 sets whilst still keeping only 1 DBT config repository? if not is there any plans to support this?

**Comment by security-dbtlabs** [comment]
Issue closed to prepare for Repository Archival
